// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJSuYgY41OOiopssxpVSVO01NA3PiBWY',
    appId: '1:46294963663:web:fdd69636525d2f7feaaeba',
    messagingSenderId: '46294963663',
    projectId: 'pls-bang',
    authDomain: 'pls-bang.firebaseapp.com',
    storageBucket: 'pls-bang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNQFgRa0IQFqXmEV242WP_uA2dQMg5T8',
    appId: '1:46294963663:android:f2c350b6c039b612eaaeba',
    messagingSenderId: '46294963663',
    projectId: 'pls-bang',
    storageBucket: 'pls-bang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAxwVcjGvwhL9icXJcFWXYFOG2_LL6v8I',
    appId: '1:46294963663:ios:a35ef07fdfcd0634eaaeba',
    messagingSenderId: '46294963663',
    projectId: 'pls-bang',
    storageBucket: 'pls-bang.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAxwVcjGvwhL9icXJcFWXYFOG2_LL6v8I',
    appId: '1:46294963663:ios:4ef3134fc84a875ceaaeba',
    messagingSenderId: '46294963663',
    projectId: 'pls-bang',
    storageBucket: 'pls-bang.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp.RunnerTests',
  );
}
